import { yekanBakh } from "@/config/font";
import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "ثبت نام",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="fa" dir="rtl">
      <body suppressHydrationWarning={true}>
        <div className={yekanBakh.className}>
          {children}
          <Toaster />
        </div>
      </body>
    </html>
  );
}
