import { yekanBakh } from "@/config/font";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "ثبت نام",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <div className={yekanBakh.className}>{children}</div>
      </body>
    </html>
  );
}
