import type { Metadata } from "next";
import "./globals.css";
import { iranYekan } from "@/config/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={iranYekan.className}>{children}</body>
    </html>
  );
}
